### ISSUE TITLE
Items not in correct category

### ISSUE THREAD

**Issue by Claudio140** [Murnto/FactorioData#1]
Hi,
I'm playing with Bob's Mods F12 and found a small error on your site: The recipe of Lithium perchlorate shows that you can find it in the "Bob's materials" tab of your inventory, but actually it is in "Bob's Fluids" and its name is Lithium chloride Electrolysis.

Maybe this occurs with other items as well, I haven't checked others yet. Would be nice if this would get fixed.

**Comment by Murnto** [comment]
This appears to be due to 'Lithium perchlorate' (the item/fluid) being a member of the 'bob-resource-chemical' subgroup, while 'Lithium chloride Electrolysis' (the recipe) is a member is a member of the 'bob-fluid-electrolysis' group.

Current behavior simply uses the the subgroup of the item for display instead of the subgroup of the recipe chosen for the popup display.

**Comment by Murnto** [comment]
Fixed in 19afb21
