### ISSUE TITLE
Lock Speed function does not work with Ratio View (adding items while in Ratio tab)

### ISSUE THREAD

**Issue by Cutelilduck** [Murnto/FactorioData#4]
**Edit:** Posted without desc, woops!

**Edit2:** I figured it out. Removed my long description.

Lock Speed does not work with Ratio View, only for Recipe. Ratio View will hold the most recent u/m value and apply it to everything. Fortunately, switching back to the Recipe Tab does not lose what was there before. 

Apologies for opening another one. Thanks for the update!

**Comment by Cutelilduck** [comment]
I edited my original issue description. Hit enter by accident. The issue is now described. This is for github email notification.

**Comment by Murnto** [comment]
Due to how the logic for Ratio view was originally written, I believe it's not feasible to implement locking  speed in Ratio view without rewriting the majority of it. Locking the speed in Recipe view was a hacked together solution as is.

The likely 'fix' for this will be to simply hide the lock speed toggle in ratio view.

**Comment by Cutelilduck** [comment]
No problem, figured it was a backend thing. Do you want me to close this?
